# Guide to Accessing WRDS via Python

Author: Zanele Munyikwa  
Date: June 25, 2019  
Last Updated: June 25, 2019

Based on Tutorial @ https://wrds-www.wharton.upenn.edu/pages/support/programming-wrds/programming-python/querying-wrds-data-python/

<a href='#section1'> 1. Using the WRDS module</a>  
<a href='#section2'> 2. Managing Connections</a>   
<a href='#section3'> 3. Querying Data Structure</a>     
<a href='#section4'> 4. Querying WRDS Data</a>    
<a href='#section5'> 5. Joining Data from Separate Datasets  </a>     
<a href='#section6'> 6. Passing Parameters to SQL</a>

<a id= 'section1'></a>

## Using WRDS Module

In [2]:
#import libraries
import wrds

In [3]:
db = wrds.Connection(wrds_username='zmunyikw')  #this command will pull up a prompt the first time it's run
#db.create_pgpass_file() #only need to run this once, and it makes it so that we don't have to repeatedly put in our username and password

Loading library list...
Done

In [4]:
help(db.get_table)

Help on method get_table in module wrds.sql:

get_table(library, table, obs=-1, offset=0, columns=None, coerce_float=None, index_col=None, date_cols=None) method of wrds.sql.Connection instance
    Creates a data frame from an entire table in the database.

    :param sql: SQL code in string object.
    :param library: Postgres schema name.

    :param obs: (optional) int, default: -1
        Specifies the number of observations to pull from the table.
        An integer less than 0 will return the entire table.
    :param offset: (optional) int, default: 0
        Specifies the starting point for the query.
        An offset of 0 will start selecting from the beginning.
    :param columns: (optional) list or tuple, default: None
        Specifies the columns to be included in the output data frame.
    :param coerce_float: (optional) boolean, default: True
        Attempt to convert values to non-string, non-numeric objects
        to floating point. Can result in loss of precision.
    :param date_cols: (optional) list or dict, default: None
        - List of column names to parse as date
        - Dict of ``{column_name: format string}``
            where format string is
              strftime compatible in case of parsing string times or
              is one of (D, s, ns, ms, us) in case of parsing
                integer timestamps
        - Dict of ``{column_name: arg dict}``,
            where the arg dict corresponds to the keyword arguments of
              :func:`pandas.to_datetime`
    :param index_col: (optional) string or list of strings,
      default: None
        Column(s) to set as index(MultiIndex)

    :rtype: pandas.DataFrame

    Usage ::
    >>> data = db.get_table('wrdssec_all', 'dforms', obs=1000, columns=['cik', 'fdate', 'coname'])
    >>> data.head()
        cik        fdate       coname
        0000000003 1995-02-15  DEFINED ASSET FUNDS MUNICIPAL INVT TR FD NEW Y...
        0000000003 1996-02-14  DEFINED ASSET FUNDS MUNICIPAL INVT TR FD NEW Y...
        0000000003 1997-02-19  DEFINED ASSET FUNDS MUNICIPAL INVT TR FD NEW Y...
        0000000003 1998-03-02  DEFINED ASSET FUNDS MUNICIPAL INVT TR FD NEW Y...
        0000000003 1998-03-10  DEFINED ASSET FUNDS MUNICIPAL INVT TR FD NEW Y..
        ...

No matter which wrds method you use, your data results are always returned as a Pandas DataFrame. Pandas is a popular Python module that, together with NumPy, forms the basis for most numeric data manipulation in Python. The pandas module provides powerful data manipulation capabilities at a granular degree of control over your output.

<a id= 'section2'></a>

## Managing Connections  <font color=red> IMPORTANT!! </font>

WRDS users are permitted up to 5 simultaneous connections to our Postgres data backend. For Python users, that means you may use wrds.Connection() up to five times before being denied additional connections.

The best way to manage this, is to properly close out your connection to WRDS once you are done with it. With the Python wrds module, you simply use the close() method like so:

`import wrds  
db = wrds.Connection()  
data = db.raw_sql("select * from djones.djdaily")   
db.close()`

You should always disconnect using close() when you:

- Exit your Python environment
- Finish running your program
- Complete your data query download step, and want to move onto another.

otherwise you have to wait until it tunes out or try to close the connections you have open if you can somehow access them...

<a id= 'section3'></a>

## Querying Dataset Structure

"Data at WRDS is organized in a hierarchical manner by vendor (e.g. crsp), referred to at the top-level as libraries. Each library contains a number of component tables or datasets (e.g. dsf) which contain the actual data in tabular format, with column headers called variables (such as date, askhi, bidlo, etc)."

In [5]:
db.list_libraries() #list all available libraries at WRDS

['wrds_lib_internal',
 'gmi_all_new',
 'secsamp_all_new',
 'compnad',
 'mflinks_all_new',
 'comp_ratings',
 'morningstar_cisdm',
 'crsp_a_treasuries',
 'infogroup_residential',
 'crsp_q_treasuries',
 'crsp_q_indexhist',
 'lspdsamp',
 'optionmsamp_europe',
 'ktmine_patents_samp',
 'optionmsamp_us',
 'omtrial',
 'ppubsamp_d4d_new',
 'ravenpack_trial',
 'rpnasamp',
 'crsp_q_mutualfunds',
 'ginsight_basic',
 'ginsight_common',
 'reprisk_sample',
 'ppubsamp_d4d',
 'mrktsamp_cds',
 'aha',
 'mrktsamp_msf',
 'ims_obp_trial',
 'infogroupsamp_residential',
 'wappsamp',
 'imssamp',
 'sustsamp',
 'repsamp',
 'ifgrsamp',
 'infogroupsamp_business',
 'mrktsamp',
 'hfrsamp_hfrdb',
 'mrktsamp_cdx',
 'twoiq_samp',
 'lvnsamp',
 'twoiqsmp',
 'hfrsamp',
 'zacksamp',
 'risksamp',
 'bvd_orbis_medium',
 'bank',
 'compmcur',
 'compsamp',
 'crspsamp',
 'compa',
 'hfr',
 'fisd_naic',
 'ravenpack_dj',
 'tr_13f',
 'bvd_orbis_large',
 'tr_worldscope',
 'bvd_orbis_small',
 'ciq_ratings',
 'comp_snapshot',
 'tr_mutualfunds',
 'ravenpack_dj_new',
 'ravenpack_pr_new',
 'bvd_ama_large',
 'bvd_ama_medium',
 'bvd_ama_small',
 'bvd_ama_verylarge',
 'ahasamp',
 'boardex_trial',
 'aha_sample',
 'trace_enhanced',
 'trace_standard',
 'crsp_a_indexes',
 'crsp_a_stock',
 'contrib_char_returns',
 'calcbench_trial',
 'zacks',
 'compsamp_snapshot',
 'eurekahedge_sample',
 'hbase_sample',
 'macrofin_comm_trade',
 'ff_all_new',
 'taqm_2003',
 'ciq_common',
 'audit',
 'blab',
 'revere',
 'bvd',
 'bvdlgcy',
 'bvdsamp',
 'tr_ibes',
 'taqm_2009',
 'snlsamp_fig',
 'block',
 'comph',
 'risk_directors',
 'infogroup_residential_new',
 'infogroup_business_academic',
 'boardsmp',
 'crsp_a_ccm_new',
 'taqm_2010',
 'audit_audit_comp',
 'comscore',
 'comp_bank',
 'taqm_2014',
 'msfanly',
 'compdcur',
 'comp_execucomp',
 'comp_global',
 'calcbnch',
 'centris',
 'ciqsamp',
 'clrvt',
 'clrvtsmp',
 'csmar',
 'compb',
 'emdb',
 'compg',
 'compm',
 'compsnap',
 'contrib',
 'etfg',
 'crsp',
 'ginsight',
 'crspa',
 'gmi',
 'crspq',
 'dealscan',
 'djones',
 'dmef',
 'doe',
 'etfgsamp',
 'eureka',
 'evts',
 'execcomp',
 'factset',
 'ff',
 'fisd',
 'fisdsamp',
 'wrdssec',
 'frb',
 'fssamp',
 'ftse',
 'ftsesamp',
 'govpxsmp',
 'gsi',
 'hbase',
 'govpx',
 'hbsamp',
 'ibes',
 'ibeskpi',
 'ifgr',
 'ims',
 'iri',
 'issm',
 'kld',
 'ktmine',
 'ktsamp',
 'levin',
 'lspd',
 'macrofin',
 'mfl',
 'ibescorp',
 'msrb',
 'nastraq',
 'reprisk',
 'optionm',
 'pacap',
 'phlx',
 'ppublica',
 'ppubsamp',
 'public',
 'pwt',
 'rent',
 'risk',
 'rpna',
 'secsamp',
 'snapsamp',
 'snl',
 'snlsamp',
 'sprat',
 'sustain',
 'taq',
 'taqmsec',
 'tass',
 'totalq',
 'toyo',
 'trace',
 'trown',
 'trsdcgs',
 'trws',
 'twoiq',
 'wcai',
 'wqa',
 'wrdsapps',
 'fisd_fisd',
 'etfg_samp',
 'sdc',
 'taqm_2016',
 'tr_dealscan',
 'ciq_capstrct',
 'ciq',
 'risk_governance',
 'crsp_a_ccm',
 'tr_ibes_guidance',
 'factsamp_revere',
 'wrdsrpts_rep_usage',
 'wrdsrpts',
 'boardex',
 'comp_segments_hist',
 'iss_incentive_lab',
 'iss_incentive_lab_europe',
 'kld_histall',
 'ravenpack_common',
 'ravenpack_pr',
 'compbd',
 'morningstar_cisdm_new',
 'cisdm',
 'taqm_2008',
 'taqm_2013',
 'comp_global_daily',
 'compgd',
 'comp_bank_daily',
 'taqm_2011',
 'taqm_2015',
 'comp_segments_hist_daily',
 'compseg',
 'taqm_2012',
 'compsegd',
 'otc_endofday',
 'otc',
 'tr_insiders',
 'tfn',
 'wrdssec_common',
 'taqm_2004',
 'taqm_2005',
 'taqm_2006',
 'taqm_2007',
 'markit',
 'wrdssec_secsa',
 'comp',
 'compd',
 'taqm_2017',
 'taqm_2018',
 'taqm_2019',
 'msfinst',
 'cboe',
 'crspm']

In [6]:
#Select a library, here we've select crsp, and then list all the tables within that library
db.list_tables(library="crsp")

['acti',
 'asia',
 'asib',
 'asic',
 'asio',
 'asix',
 'bmdebt',
 'bmheader',
 'bmpaymts',
 'bmquotes',
 'bmyield',
 'bndprt06',
 'bndprt12',
 'bxcalind',
 'bxdlyind',
 'bxmthind',
 'bxquotes',
 'bxyield',
 'cap',
 'ccm_lookup',
 'ccm_qvards',
 'ccmxpf_linktable',
 'ccmxpf_lnkhist',
 'ccmxpf_lnkrng',
 'ccmxpf_lnkused',
 'comphead',
 'comphist',
 'compmaster',
 'contact_info',
 'crsp_cik_map',
 'crsp_daily_data',
 'crsp_header',
 'crsp_monthly_data',
 'crsp_names',
 'crsp_portno_map',
 'crsp_ziman_daily_index',
 'crsp_ziman_monthly_index',
 'cs20yr',
 'cs5yr',
 'cs90d',
 'cst_hist',
 'daily_nav',
 'daily_nav_ret',
 'daily_returns',
 'dividends',
 'dport1',
 'dport2',
 'dport3',
 'dport4',
 'dport5',
 'dport6',
 'dport7',
 'dport8',
 'dport9',
 'dsbc',
 'dsbo',
 'dse',
 'dse62',
 'dse62delist',
 'dse62dist',
 'dse62exchdates',
 'dse62names',
 'dse62nasdin',
 'dse62shares',
 'dseall',
 'dseall62',
 'dsedelist',
 'dsedist',
 'dseexchdates',
 'dsenames',
 'dsenasdin',
 'dseshares',
 'dsf',
 'dsf62',
 'dsfhdr',
 'dsfhdr62',
 'dsi',
 'dsi62',
 'dsia',
 'dsib',
 'dsic',
 'dsio',
 'dsir',
 'dsix',
 'dsiy',
 'dsp500',
 'dsp500list',
 'dsp500p',
 'dssc',
 'dsso',
 'eod_cap',
 'eod_sector',
 'eod_vg',
 'erdport1',
 'erdport2',
 'erdport3',
 'erdport4',
 'erdport5',
 'erdport6',
 'erdport7',
 'erdport8',
 'erdport9',
 'ermport1',
 'ermport2',
 'ermport3',
 'ermport4',
 'ermport5',
 'fbpri',
 'fbyld',
 'front_load',
 'front_load_det',
 'front_load_grp',
 'fund_fees',
 'fund_hdr',
 'fund_hdr_hist',
 'fund_names',
 'fund_style',
 'fund_summary',
 'fund_summary2',
 'fwdask06',
 'fwdask12',
 'fwdave06',
 'fwdave12',
 'fwdbid06',
 'fwdbid12',
 'hldask06',
 'hldask12',
 'hldave06',
 'hldave12',
 'hldbid06',
 'hldbid12',
 'holdings',
 'index_descriptions',
 'index_type_map',
 'mbi',
 'mbmdat',
 'mbmhdr',
 'mbx',
 'mbxid',
 'mcti',
 'mfdbname',
 'mhista',
 'mhistn',
 'mhistq',
 'monthly_nav',
 'monthly_returns',
 'monthly_tna',
 'monthly_tna_ret_nav',
 'mport1',
 'mport2',
 'mport3',
 'mport4',
 'mport5',
 'mse',
 'mse62',
 'mse62delist',
 'mse62dist',
 'mse62exchdates',
 'mse62names',
 'mse62nasdin',
 'mse62shares',
 'mseall',
 'mseall62',
 'msedelist',
 'msedist',
 'mseexchdates',
 'msenames',
 'msenasdin',
 'mseshares',
 'msf',
 'msf62',
 'msfhdr',
 'msfhdr62',
 'msi',
 'msi62',
 'msia',
 'msib',
 'msic',
 'msio',
 'msir',
 'msix',
 'msiy',
 'msp500',
 'msp500list',
 'msp500p',
 'portnomap',
 'priask06',
 'priask12',
 'priave06',
 'priave12',
 'pribid06',
 'pribid12',
 'price_type',
 'property_type',
 'qcti',
 'qsia',
 'qsib',
 'qsic',
 'qsio',
 'qsix',
 'rear_load',
 'rear_load_det',
 'rear_load_grp',
 'rebala',
 'rebaln',
 'rebalq',
 'reit_type',
 'riskfree',
 's6z_del',
 's6z_dind',
 's6z_dis',
 's6z_dp_dly',
 's6z_ds_dly',
 's6z_hdr',
 's6z_indhdr',
 's6z_mdel',
 's6z_mind',
 's6z_mth',
 's6z_nam',
 's6z_ndi',
 's6z_shr',
 'saz_del',
 'saz_dind',
 'saz_dis',
 'saz_dp_dly',
 'saz_ds_dly',
 'saz_hdr',
 'saz_indhdr',
 'saz_mdel',
 'saz_mind',
 'saz_mth',
 'saz_nam',
 'saz_ndi',
 'saz_shr',
 'sechead',
 'sechist',
 'sector',
 'sfz_dind',
 'sfz_indhdr',
 'sfz_mbr',
 'sfz_mind',
 'sfz_portd',
 'sfz_portm',
 'sfz_rb',
 'stock_qvards',
 'stocknames',
 'stocknames62',
 'sub_property_type',
 'tfz_dly',
 'tfz_dly_cd',
 'tfz_dly_cpi',
 'tfz_dly_ft',
 'tfz_dly_rf2',
 'tfz_dly_ts2',
 'tfz_idx',
 'tfz_iss',
 'tfz_mast',
 'tfz_mth',
 'tfz_mth_bp',
 'tfz_mth_cd',
 'tfz_mth_cpi',
 'tfz_mth_fb',
 'tfz_mth_ft',
 'tfz_mth_rf',
 'tfz_mth_rf2',
 'tfz_mth_ts',
 'tfz_mth_ts2',
 'tfz_pay',
 'vg',
 'yldask06',
 'yldask12',
 'yldave06',
 'yldave12',
 'yldbid06',
 'yldbid12',
 'ziman_reit_info',
 'zr_hdrnames']

In [7]:
#alternatively could select comp for compustat
db.list_tables(library="comp")

['aco_amda',
 'aco_imda',
 'aco_indfnta',
 'aco_indfntq',
 'aco_indfntytd',
 'aco_indsta',
 'aco_indstq',
 'aco_indstytd',
 'aco_notesa',
 'aco_notesq',
 'aco_notessa',
 'aco_notesytd',
 'aco_pnfnda',
 'aco_pnfndq',
 'aco_pnfndytd',
 'aco_pnfnta',
 'aco_pnfntq',
 'aco_pnfntytd',
 'aco_transa',
 'aco_transq',
 'aco_transsa',
 'aco_transytd',
 'adsprate',
 'anncomp',
 'asec_amda',
 'asec_imda',
 'asec_notesa',
 'asec_notesq',
 'asec_transa',
 'asec_transq',
 'bank_aacctchg',
 'bank_adesind',
 'bank_afnd1',
 'bank_afnd2',
 'bank_afnddc1',
 'bank_afnddc2',
 'bank_afntind',
 'bank_funda',
 'bank_funda_fncd',
 'bank_fundq',
 'bank_fundq_fncd',
 'bank_iacctchg',
 'bank_idesind',
 'bank_ifndq',
 'bank_ifndytd',
 'bank_ifntq',
 'bank_ifntytd',
 'bank_names',
 'bank_namesq',
 'chars',
 'co_aacctchg',
 'co_aaudit',
 'co_adesind',
 'co_adjfact',
 'co_afnd1',
 'co_afnd2',
 'co_afnddc1',
 'co_afnddc2',
 'co_afntind1',
 'co_afntind2',
 'co_ainvval',
 'co_amkt',
 'co_busdescl',
 'co_cotype',
 'co_filedate',
 'co_fortune',
 'co_hgic',
 'co_iacctchg',
 'co_iaudit',
 'co_idesind',
 'co_ifndq',
 'co_ifndsa',
 'co_ifndytd',
 'co_ifntq',
 'co_ifntsa',
 'co_ifntytd',
 'co_imkt',
 'co_industry',
 'co_ipcd',
 'co_mthly',
 'co_offtitl',
 'codirfin',
 'colev',
 'company',
 'coperol',
 'currency',
 'dd_group',
 'dd_group_xref',
 'dd_item',
 'dd_package',
 'deferredcomp',
 'directorcomp',
 'ecind_desc',
 'ecind_mth',
 'ex_black',
 'ex_header',
 'exnames',
 'exrt_dly',
 'exrt_mth',
 'filings',
 'funda',
 'funda_fncd',
 'fundq',
 'fundq_fncd',
 'g_chars',
 'g_co_aaudit',
 'g_co_adesind',
 'g_co_afnd1',
 'g_co_afnd2',
 'g_co_afnddc1',
 'g_co_afnddc2',
 'g_co_afntind1',
 'g_co_afntind2',
 'g_co_ainvval',
 'g_co_hgic',
 'g_co_iaudit',
 'g_co_idesind',
 'g_co_ifndq',
 'g_co_ifndsa',
 'g_co_ifndytd',
 'g_co_ifntq',
 'g_co_ifntsa',
 'g_co_ifntytd',
 'g_co_industry',
 'g_co_ipcd',
 'g_co_offtitl',
 'g_company',
 'g_currency',
 'g_ecind_desc',
 'g_ecind_mth',
 'g_exrt_dly',
 'g_exrt_mth',
 'g_funda',
 'g_funda_fncd',
 'g_fundq',
 'g_fundq_fncd',
 'g_idx_daily',
 'g_idx_index',
 'g_idx_mth',
 'g_idxcst_his',
 'g_names',
 'g_names_ix',
 'g_names_ix_cst',
 'g_namesq',
 'g_sec_adesind',
 'g_sec_adjfact',
 'g_sec_afnd',
 'g_sec_afnddc',
 'g_sec_afnt',
 'g_sec_divid',
 'g_sec_dprc',
 'g_sec_dtrt',
 'g_sec_history',
 'g_sec_idesind',
 'g_sec_ifnd',
 'g_sec_ifnt',
 'g_sec_split',
 'g_secd',
 'g_secnamesd',
 'g_security',
 'g_sedolgvkey',
 'idx_ann',
 'idx_anndes',
 'idx_daily',
 'idx_index',
 'idx_mth',
 'idx_qrt',
 'idx_qrtdes',
 'idxcst_his',
 'io_qaggregate',
 'io_qbuysell',
 'io_qchanges',
 'io_qfloatadj',
 'io_qholders',
 'it_mbuysell',
 'it_msummary',
 'it_r_rltn',
 'ltawdtab',
 'names',
 'names_aco_indsta',
 'names_aco_indstq',
 'names_aco_pnfnda',
 'names_aco_pnfndq',
 'names_adsprate',
 'names_ix',
 'names_ix_cst',
 'names_seg',
 'namesd',
 'namesm',
 'namesq',
 'outstandingawards',
 'pension',
 'person',
 'planbasedawards',
 'r_accstd',
 'r_acqmeth',
 'r_auditors',
 'r_auopic',
 'r_balpres',
 'r_cf_formt',
 'r_co_status',
 'r_coindpre',
 'r_compstat',
 'r_consol',
 'r_country',
 'r_cstclscd',
 'r_datacode',
 'r_datafmt',
 'r_divtaxmarker',
 'r_docsrce',
 'r_ex_codes',
 'r_exchgtier',
 'r_exrt_typ',
 'r_fndfntcd',
 'r_footnts',
 'r_foricd',
 'r_giccd',
 'r_hcalendr',
 'r_idxclscd',
 'r_inactvcd',
 'r_incstats',
 'r_indfmt',
 'r_indsec',
 'r_invval',
 'r_issuetyp',
 'r_majidxcl',
 'r_mic_codes',
 'r_naiccd',
 'r_notetype',
 'r_ntsubtype',
 'r_offcrso',
 'r_ogmethod',
 'r_opinions',
 'r_prc_stat',
 'r_qsrcdoc',
 'r_sec_stat',
 'r_secannfn',
 'r_sectors',
 'r_siccd',
 'r_spiicd',
 'r_spmicd',
 'r_statalrt',
 'r_states',
 'r_stko',
 'r_titles',
 'r_updates',
 'sec_adesind',
 'sec_adjfact',
 'sec_afnd',
 'sec_afnddc',
 'sec_afnt',
 'sec_divid',
 'sec_dprc',
 'sec_dtrt',
 'sec_history',
 'sec_idesind',
 'sec_ifnd',
 'sec_ifnt',
 'sec_mdivfn',
 'sec_mshare',
 'sec_msptfn',
 'sec_mth',
 'sec_mthdiv',
 'sec_mthprc',
 'sec_mthspt',
 'sec_mthtrt',
 'sec_shortint',
 'sec_spind',
 'sec_split',
 'secd',
 'secm',
 'security',
 'sedolgvkey',
 'seg_ann',
 'seg_annfund',
 'seg_customer',
 'seg_geo',
 'seg_naics',
 'seg_product',
 'seg_type',
 'spidx_cst',
 'spind',
 'spind_dly',
 'spind_mth',
 'stgrttab',
 'wrds_seg_customer',
 'wrds_seg_geo',
 'wrds_seg_product',
 'wrds_segmerged',
 'xfl_column',
 'xfl_table']

Can also view list of variables and tables on wrds as well, since for long lists, you end up with ellipses
https://wrds-web.wharton.upenn.edu/wrds/tools/variable.cfm?library_id=7&file_id=95302

In [8]:
#to view the column headers/variables within a dataset
db.describe_table(library="crsp", table="ccmxpf_linktable")

Approximately 76486 rows in crsp.ccmxpf_linktable.

        name  nullable              type
0      gvkey      True        VARCHAR(6)
1   linkprim      True        VARCHAR(1)
2       liid      True        VARCHAR(3)
3   linktype      True        VARCHAR(2)
4    lpermno      True  DOUBLE PRECISION
5    lpermco      True  DOUBLE PRECISION
6   usedflag      True  DOUBLE PRECISION
7     linkdt      True              DATE
8  linkenddt      True              DATE

In [9]:
db.describe_table(library="comp", table="funda")

Approximately 804155 rows in comp.funda.

         name  nullable              type
0       gvkey      True        VARCHAR(6)
1    datadate      True              DATE
2       fyear      True  DOUBLE PRECISION
3      indfmt      True       VARCHAR(12)
4      consol      True        VARCHAR(2)
5      popsrc      True        VARCHAR(1)
6     datafmt      True       VARCHAR(12)
7         tic      True        VARCHAR(8)
8       cusip      True        VARCHAR(9)
9        conm      True       VARCHAR(57)
10    acctchg      True        VARCHAR(8)
11    acctstd      True        VARCHAR(8)
12    acqmeth      True        VARCHAR(2)
13       adrr      True  DOUBLE PRECISION
14       ajex      True  DOUBLE PRECISION
15        ajp      True  DOUBLE PRECISION
16       bspr      True        VARCHAR(8)
17     compst      True        VARCHAR(8)
18      curcd      True        VARCHAR(3)
19     curncd      True        VARCHAR(3)
20     currtr      True  DOUBLE PRECISION
21    curuscn      True  DOUBLE PRECISION
22      final      True        VARCHAR(2)
23        fyr      True  DOUBLE PRECISION
24      ismod      True  DOUBLE PRECISION
25       ltcm      True        VARCHAR(8)
26        ogm      True        VARCHAR(8)
27      pddur      True  DOUBLE PRECISION
28        scf      True  DOUBLE PRECISION
29        src      True  DOUBLE PRECISION
..        ...       ...               ...
918    xuwrei      True  DOUBLE PRECISION
919     xuwti      True  DOUBLE PRECISION
920       iid      True        VARCHAR(3)
921     exchg      True  DOUBLE PRECISION
922       cik      True       VARCHAR(10)
923    costat      True        VARCHAR(1)
924       fic      True        VARCHAR(3)
925    naicsh      True  DOUBLE PRECISION
926      sich      True  DOUBLE PRECISION
927   cshtr_c      True  DOUBLE PRECISION
928   dvpsp_c      True  DOUBLE PRECISION
929   dvpsx_c      True  DOUBLE PRECISION
930    prcc_c      True  DOUBLE PRECISION
931    prch_c      True  DOUBLE PRECISION
932    prcl_c      True  DOUBLE PRECISION
933   adjex_c      True  DOUBLE PRECISION
934   cshtr_f      True  DOUBLE PRECISION
935   dvpsp_f      True  DOUBLE PRECISION
936   dvpsx_f      True  DOUBLE PRECISION
937    mkvalt      True  DOUBLE PRECISION
938    prcc_f      True  DOUBLE PRECISION
939    prch_f      True  DOUBLE PRECISION
940    prcl_f      True  DOUBLE PRECISION
941   adjex_f      True  DOUBLE PRECISION
942      rank      True  DOUBLE PRECISION
943        au      True        VARCHAR(8)
944      auop      True        VARCHAR(8)
945    auopic      True        VARCHAR(1)
946     ceoso      True        VARCHAR(1)
947     cfoso      True        VARCHAR(1)

[948 rows x 3 columns]

<a id= 'section4'></a>

## Querying WRDS Data

### get_table() fetches data by matching library and dataset, with the ability to filter using different parameters

In [35]:
data = db.get_table(library='djones', table='djdaily', columns=['date', 'dji'], obs=10)

### raw(sql() executes a SQL query against the specified library and dataset, allowing for highly granular data queries

According to the WRDS support documentation, the raw_sql() method is by far the most useful and popular of the wrds module's methods, allowing powerful and granular control over your data processing. Writing SQL for use with this method of fairly straightforward. All data queries are constructed in SQL the following generic manner:

In [36]:
data = db.raw_sql(sql='select date,dji from djones.djdaily LIMIT 10;', date_cols=['date'])

### get_row_count() returns the number of rows in a given dataset

In [37]:
data = db.get_row_count(library='djones', table='djdaily')

<a id= 'section5'></a>

## Joining Data from Separate Datasets

The following example will join the Compustat Fundamentals data set (comp.funda) with Compustat's pricing dataset (comp.secm), and then query for total assets and liabilities mixed with monthly close price and shares outstanding.

In [38]:
db.raw_sql("select a.gvkey, a.datadate, a.tic, a.conm, a.at, a.lt, b.prccm, b.cshoq from comp.funda a join comp.secm b on a.gvkey = b.gvkey and a.datadate = b.datadate where a.tic = 'IBM' and a.datafmt = 'STD' and a.consol = 'C' and a.indfmt = 'INDL'")

,gvkey,datadate,tic,conm,at,lt,prccm,cshoq
0,006066,1962-12-31,IBM,INTL BUSINESS MACHINES CORP,2112.301,731.700,389.999567,NaN
1,006066,1963-12-31,IBM,INTL BUSINESS MACHINES CORP,2373.857,782.119,506.999353,NaN
2,006066,1964-12-31,IBM,INTL BUSINESS MACHINES CORP,3309.152,1055.072,409.499496,NaN
3,006066,1965-12-31,IBM,INTL BUSINESS MACHINES CORP,3744.917,1166.771,498.999146,NaN
4,006066,1966-12-31,IBM,INTL BUSINESS MACHINES CORP,4660.777,1338.149,371.499662,NaN
5,006066,1967-12-31,IBM,INTL BUSINESS MACHINES CORP,5598.668,1767.067,626.999512,NaN
6,006066,1968-12-31,IBM,INTL BUSINESS MACHINES CORP,6743.430,2174.291,314.999847,NaN
7,006066,1969-12-31,IBM,INTL BUSINESS MACHINES CORP,7389.957,2112.967,364.499359,113.717
8,006066,1970-12-31,IBM,INTL BUSINESS MACHINES CORP,8539.047,2591.909,317.749634,114.587
9,006066,1971-12-31,IBM,INTL BUSINESS MACHINES CORP,9576.219,2933.837,336.499634,115.534
10,006066,1972-12-31,IBM,INTL BUSINESS MACHINES CORP,10792.398,3226.508,401.999512,116.399
11,006066,1973-12-31,IBM,INTL BUSINESS MACHINES CORP,12289.500,3477.465,246.749878,146.713
12,006066,1974-12-31,IBM,INTL BUSINESS MACHINES CORP,14027.098,3916.766,167.999878,148.259
13,006066,1975-12-31,IBM,INTL BUSINESS MACHINES CORP,15530.504,4114.705,224.249878,149.845
14,006066,1976-12-31,IBM,INTL BUSINESS MACHINES CORP,17723.203,4974.035,279.124756,150.695
15,006066,1977-12-31,IBM,INTL BUSINESS MACHINES CORP,18978.402,6359.965,273.499756,147.471
16,006066,1978-12-31,IBM,INTL BUSINESS MACHINES CORP,20771.406,7277.759,298.499878,145.810
17,006066,1979-12-31,IBM,INTL BUSINESS MACHINES CORP,24530.004,9568.734,64.374969,583.595
18,006066,1980-12-31,IBM,INTL BUSINESS MACHINES CORP,26703.008,10250.000,67.874939,583.807
19,006066,1981-12-31,IBM,INTL BUSINESS MACHINES CORP,29586.008,11425.000,56.874969,592.294
20,006066,1982-12-31,IBM,INTL BUSINESS MACHINES CORP,32541.008,12581.000,96.250000,602.406
21,006066,1983-12-31,IBM,INTL BUSINESS MACHINES CORP,37243.008,14024.000,122.000000,610.725
22,006066,1984-12-31,IBM,INTL BUSINESS MACHINES CORP,42808.012,16319.000,123.125000,612.685
23,006066,1985-12-31,IBM,INTL BUSINESS MACHINES CORP,52634.016,20644.000,155.500000,615.418
24,006066,1986-12-31,IBM,INTL BUSINESS MACHINES CORP,57814.016,23440.000,120.000000,605.923
25,006066,1987-12-31,IBM,INTL BUSINESS MACHINES CORP,63688.000,25425.000,115.500000,597.052
26,006066,1988-12-31,IBM,INTL BUSINESS MACHINES CORP,73037.000,33528.000,121.875000,589.741
27,006066,1989-12-31,IBM,INTL BUSINESS MACHINES CORP,77734.000,39225.000,94.125000,574.700
28,006066,1990-12-31,IBM,INTL BUSINESS MACHINES CORP,87568.000,44736.000,113.000000,571.391
29,006066,1991-12-31,IBM,INTL BUSINESS MACHINES CORP,92473.000,55467.000,89.000000,571.018
30,006066,1992-12-31,IBM,INTL BUSINESS MACHINES CORP,86705.000,59081.000,50.375000,571.436
31,006066,1993-12-31,IBM,INTL BUSINESS MACHINES CORP,81113.000,61375.000,56.500000,581.386
32,006066,1994-12-31,IBM,INTL BUSINESS MACHINES CORP,81091.000,57678.000,73.500000,587.710
33,006066,1995-12-31,IBM,INTL BUSINESS MACHINES CORP,80292.000,57869.000,91.375000,547.774
34,006066,1996-12-31,IBM,INTL BUSINESS MACHINES CORP,81132.000,59504.000,151.500000,507.981
35,006066,1997-12-31,IBM,INTL BUSINESS MACHINES CORP,81499.000,61683.000,104.625000,958.091
36,006066,1998-12-31,IBM,INTL BUSINESS MACHINES CORP,86100.000,66667.000,184.375000,915.907
37,006066,1999-12-31,IBM,INTL BUSINESS MACHINES CORP,87495.000,66984.000,107.875000,1784.216
38,006066,2000-12-31,IBM,INTL BUSINESS MACHINES CORP,88349.000,67725.000,85.000000,1742.900
39,006066,2001-12-31,IBM,INTL BUSINESS MACHINES CORP,88313.000,64699.000,120.960000,1723.194
40,006066,2002-12-31,IBM,INTL BUSINESS MACHINES CORP,96484.000,73702.000,77.500000,1722.367
41,006066,2003-12-31,IBM,INTL BUSINESS MACHINES CORP,104457.000,76593.000,92.680000,1694.509
42,006066,2004-12-31,IBM,INTL BUSINESS MACHINES CORP,109183.000,79436.000,98.580000,1645.592
43,006066,2005-12-31,IBM,INTL BUSINESS MACHINES CORP,105748.000,72650.000,82.200000,1573.980
44,006066,2006-12-31,IBM,INTL BUSINESS MACHINES CORP,103234.000,74728.000,97.150000,1506.483
45,006066,2007-12-31,IBM,INTL BUSINESS MACHINES CORP,120431.000,91961.000,108.100000,1385.234
46,006066,2008-12-31,IBM,INTL BUSINESS MACHINES CORP,109524.000,96059.000,84.160000,1339.096
47,006066,2009-12-31,IBM,INTL BUSINESS MACHINES CORP,109022.000,86267.000,130.900000,1305.337
48,006066,2010-12-31,IBM,INTL BUSINESS MACHINES CORP,113452.000,90280.000,146.760000,1227.993
49,006066,2011-12-31,IBM,INTL BUSINESS MACHINES CORP,116433.000,96197.000,183.880000,1163.183
50,006066,2012-12-31,IBM,INTL BUSINESS MACHINES CORP,119213.000,100229.000,191.550000,1117.368
51,006066,2013-12-31,IBM,INTL BUSINESS MACHINES CORP,126223.000,103294.000,187.570000,1054.391
52,006066,2014-12-31,IBM,INTL BUSINESS MACHINES CORP,117532.000,105518.000,160.440000,990.524
53,006066,2015-12-31,IBM,INTL BUSINESS MACHINES CORP,110495.000,96071.000,137.620000,965.729
54,006066,2016-12-31,IBM,INTL BUSINESS MACHINES CORP,117470.000,99078.000,165.990000,945.867
55,006066,2017-12-31,IBM,INTL BUSINESS MACHINES CORP,125356.000,107631.000,153.420000,922.179
56,006066,2018-12-31,IBM,INTL BUSINESS MACHINES CORP,123382.000,106453.000,113.670000,892.479

<a id= 'section6'></a>

## Passing Parameters to SQL

In [39]:
parm = {'tickers': ('0015B', '0030B', '0032A', '0033A', '0038A')}
data = db.raw_sql('SELECT datadate,gvkey,cusip FROM comp.funda WHERE tic in %(tickers)s', params=parm)

Fin   
Source: https://wrds-www.wharton.upenn.edu/pages/support/programming-wrds/programming-python/querying-wrds-data-python/

In [46]:
db.close()